version: '3.7'

services:
  postgres:
    image: postgres:15.2-alpine
    hostname: postgres
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
