version: '3.7'

services:
  postgres:
    image: postgres:10
    ports:
      - 5432:5432

  transaction_limiter:
    depends_on:
      - postgres
    container_name: transaction_limiter
    ports:
      - 5050:5050
    image: transaction_limiter
    build:
      context: .
    volumes:
      - "./transaction_limiter:/service/transaction_limiter"
      - "./requirements:/service/requirements"
      - "./tests:/service/tests"
      - "./configs:/service/configs"
    stdin_open: true    # flag to allow debugging with pdb
    tty: true           # flag to allow debugging with pdb
    user: transaction_limiter